apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: website
    app.kubernetes.io/part-of: legionella
    app.kubernetes.io/version: v0.1.0
  name: legionellawebsite
  namespace: legionella-dashboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: website
      app.kubernetes.io/part-of: legionella
      app.kubernetes.io/version: v0.1.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: website
        app.kubernetes.io/part-of: legionella
        app.kubernetes.io/version: v0.1.0
    spec:
      containers:
        - env:
          - name: APIToken
            valueFrom:
              secretKeyRef:
                key: BiodataDBAPIKey
                name: api-key
          image: quay.io/mariusdieckmann/legionellaproject:master
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
          name: website
          ports:
          - containerPort: 8080
      volumes:
        - name: config
          configMap:
            name: legionella-stable-config
---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: legionella-dashboard
spec:
  selector:
    app.kubernetes.io/name: website
    app.kubernetes.io/part-of: legionella
    app.kubernetes.io/version: v0.1.0
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website
  namespace: legionella-dashboard
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: legionellaproject.ingress.rancher.computational.bio
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: website
              port:
                number: 8080
  tls: # < placing a host in the TLS config will indicate a certificate should be created
  - hosts:
    - legionellaproject.ingress.rancher.computational.bio
    secretName: ui-legionellaproject-stable-private-cert # < cert-manager will store the created certificate in this secret.
---
